### ISSUE TITLE
Feature Request - RStudio addins for creating and modifying markdown tables

### ISSUE THREAD

**Issue by zenggyu** [matt-dray/quartostamp#2]
Hi, thanks for the great addin! It is really convenient!

I wonder if it is possible to add some additional functions for creating and modifying markdown tables, as is suggested [here](https://github.com/quarto-dev/quarto-r/issues/33).

**Comment by matt-dray** [comment]
Thanks @zenggyu. [The {remedy} package](https://thinkr-open.github.io/remedy/index.html) by @ThinkR-open is the go-to RStudio Addin for inserting (R) Markdown; {quartostamp} focuses more on the idiosyncrasies of Quarto. 

{remedy} currently has a function to insert a table skeleton:

```
|  a|  b|  c|
|--:|--:|--:|
|  1|  2|  3|
|  2|  3|  4|
```

But not yet a method for 'parsing and modifying an existing markdown table'. It may be worth raising this issue in that repo to see if they can help.

**Comment by zenggyu** [comment]
Thanks for letting me know! I am closing this issue and will open one there.
