### ISSUE TITLE
Add in `. . .` for incremental sections

### ISSUE THREAD

**Issue by Lextuga007** [matt-dray/quartostamp#9]
I'm not sure what it's called but `. . .`  works like `--` in xaringan for incremental sections rather than lines. I found it in this blog https://emitanaka.org/blog/2022-07-11-transitioning-from-xaringan-to-quarto-revealjs/transitioning-from-xaringan-to-quarto-revealjs.html

Would be great to have it add to this package - possibly called incremental sections?

**Comment by matt-dray** [comment]
I think this makes sense as a simple insertion, i.e. literally it will insert `. . .`, but just to check: were you thinking it could behave in a particular way after the user highlights some lines first (a la #6)?

**Comment by Lextuga007** [comment]
No, not the same behaviour as #6, just an additional option in the add in for "section increments".

BTW I use this add in ALL. THE. TIME! It saves so much time and a nice reminder of what is available to use too 🥇

**Comment by matt-dray** [comment]
I've got some great news for you: I'm so efficient that I appear to have already done this and subsequently forgotten about it. 🤦‍♂️

'Insert Pause' (`stamp_pause()`) will insert a `. . .`. 'Pause' is just how they refer to it in [the docs](https://quarto.org/docs/presentations/revealjs/#incremental-lists:~:text=You%20can%20also-,insert%20a%20pause,-within%20a%20slide).

**Comment by Lextuga007** [comment]
Brilliant! Now you can see how I didn't read the docs! 😊

**Comment by matt-dray** [comment]
I somehow read the docs, wrote the function and still forgot, so I think I'm worse!
